HITTA_INDUSTRY = {
    "Bil, Båt & Motor": {
        "Begagnade bilar": {},
        "Bensinstationer": {},
        "Bilbesiktning": {},
        "Bildelar & Biltillbehör": {},
        "Bilel- & Bilelektronikverkstäder": {},
        "Bilförsäljning": {},
        "Bilglas": {},
        "Bilhandlare": {},
        "Bilinredningar": {},
        "Billacker": {},
        "Billackering, lastbilslackering": {},
        "Billarm": {},
        "Bilplåt- & Billackeringsverkstäder": {},
        "Bilplåtslagerier": {},
        "Bilradio & Bilstereoutrustning": {},
        "Bilskrot": {},
        "Biltest": {},
        "Biluthyrning": {},
        "Bilverkstäder": {},
        "Bilvård": {},
        "Bilvårdsutrustning": {},
        "Bogsering, sjötransport": {},
        "Bryggor, bryggtillbehör": {},
        "Bärgningar": {},
        "Båtar & Båttillbehör": {},
        "Båtbesiktning": {},
        "Båtbyggare": {},
        "Båtel, -elektronik": {},
        "Båtförmedling": {},
        "Båtklubbar": {},
        "Båtmotorer - tillverkare, grossister": {},
        "Båtmotorer, reparationer, tillbehör": {},
        "Båttillbehör": {},
        "Båtuthyrning": {},
        "Båtvarv": {},
        "Djurtransporter": {},
        "Drivmedelsutrustningar": {},
        "Däckservice & Däckförsäljning": {},
        "Däckverkstad": {},
        "Elfordon, mopedbilar": {},
        "Elmotorer, generatorer": {},
        "Fartygsservice, varvsutrustning": {},
        "Fordons-, bilverkstadsutrustningar": {},
        "Fordonsbesiktningar": {},
        "Fordonsgas": {},
        "Fordonsuthyrning": {},
        "Fyrhjulingar": {},
        "Gästhamnar": {},
        "Hamnar": {},
        "Husbilar, Husvagnar & Släpvagnar": {},
        "Husbils-, Släpvagns- & Husvagnsuthyrning": {},
        "Husvagnsreparationer & Tillbehör": {},
        "Infartsparkeringar": {},
        "Lackering, laminering": {},
        "Lastbilar, Bussar & Specialfordon": {},
        "Lastbilspåbyggnader": {},
        "Lastbilsreparationer": {},
        "Marina": {},
        "Mopedförsäljning & Mopedverkstäder": {},
        "Motorcyklar, Försäljning & Service": {},
        "Motorreparationer, -renoveringar": {},
        "Naturhamnar": {},
        "Nya bilar": {},
        "Parkeringsbolag, -utrustning": {},
        "Parkeringshus, parkeringar": {},
        "Parkeringsservice": {},
        "Rostfria arbeten, material": {},
        "Rostskyddsbehandlingar": {},
        "Sjömackar": {},
        "Sjöservice": {},
        "Skeppsvarv": {},
        "Skrot, skrothandlare": {},
        "Snöskotrar": {},
        "Trafikskolor": {},
        "Trafikövningsplatser": {},
        "Vattenskotrar": {},
        "Veteranbilar, reservdelar": {}
    },
    "Butiker & Shopping": {
        "Accessoarer": {},
        "Akvarium, akvarieuthyrning": {},
        "Antenner": {},
        "Antikvariat": {},
        "Antikviteter": {},
        "Apotek": {},
        "Apoteksombud": {},
        "Arbetarskyddsmaterial": {},
        "Arbetskläder": {},
        "Armaturfabriker": {},
        "Atg-ombud": {},
        "Auktioner": {},
        "Baby- & Barnutrustning": {},
        "Badrumsinredningar": {},
        "Bagerier": {},
        "Barn- & Babykläder": {},
        "Barnartiklar": {},
        "Barnvagnsbutiker": {},
        "Bastuanläggningar, aggregat": {},
        "Begagnatförsäljning, bytesaffärer": {},
        "Belysningar & Lampaffärer": {},
        "Bensinstationer": {},
        "Beslag": {},
        "Bijouteributiker": {},
        "Bingo": {},
        "Blommogram": {},
        "Blommor": {},
        "Blomsterhandel": {},
        "Bokhandel": {},
        "Bokklubbar": {},
        "Borstar, penslar": {},
        "Bröllopsplanering": {},
        "Butiksinredningar": {},
        "Bygg-, arbetsmaskiner": {},
        "Byggvaror & Järnaffärer": {},
        "Byggvaruhus": {},
        "Casinon": {},
        "CD & DVD": {},
        "Charkuterivaror": {},
        "Choklad": {},
        "Cykelförsäljning & Cykelverkstäder": {},
        "Cyklar": {},
        "Cyklar - reparationer": {},
        "Cyklar - uthyrning": {},
        "Damkläder": {},
        "Dammsugare": {},
        "Datorer & Datortillbehör": {},
        "Datorgrafik": {},
        "Dekorationsmaterial": {},
        "Delikatesser": {},
        "Diskmaskiner": {},
        "Djuraffärer": {},
        "Djurfoder, artiklar": {},
        "Drivmedelsutrustningar": {},
        "E-handel": {},
        "Ekologiska livsmedel": {},
        "Elartiklar": {},
        "Fanér": {},
        "Fest- & Högtidskläder": {},
        "Festartiklar": {},
        "Flaggor, flaggstänger": {},
        "Fordonsgas": {},
        "Fotoaffärer": {},
        "Frimärken, tillbehör": {},
        "Färdiglagad mat": {},
        "Färg & Tapeter": {},
        "Färganalys": {},
        "Förgyllning": {},
        "Garderober": {},
        "Garner, Tyger & Sybehör": {},
        "Gatumöbler, utrustning": {},
        "Glas & Porslin": {},
        "Glasbruk": {},
        "Glasmåleri, konstglasmästeri": {},
        "Glass": {},
        "Golfbutiker": {},
        "Golvbutiker": {},
        "Golvvärme": {},
        "Golvvård": {},
        "Guld & Juveler": {},
        "Handarbeten": {},
        "Handelsträdgårdar": {},
        "Handskar": {},
        "Handskbutiker & Väskbutiker": {},
        "Hantverk & Hemslöjd": {},
        "Hattar, mössor": {},
        "Hemelektronik & Hushållsapparater": {},
        "Heminredning": {},
        "Hemtextilier & Gardiner": {},
        "Herrkläder": {},
        "Hobbyartiklar": {},
        "Homestaging": {},
        "Hushållsartiklar": {},
        "Hushållsutrustning, vitvaror": {},
        "Hygienartiklar": {},
        "Hyllor, hyllsystem": {},
        "Högtrycksutrustningar": {},
        "Inredningsartiklar": {},
        "Instrument": {},
        "Is, ismaskiner": {},
        "Jakt- & Fiskeutrustning": {},
        "Jeans": {},
        "Jordleverantörer": {},
        "Jour- & Servicebutiker": {},
        "Järn, stål": {},
        "Järnvaror": {},
        "Kakel & Klinkers": {},
        "Kattuppfödning": {},
        "Kiosker": {},
        "Klockaffärer & Urmakare": {},
        "Klädaffärer": {},
        "Kläder - uthyrning": {},
        "Kompostering, utrustning": {},
        "Konfektyr & Godisaffärer": {},
        "Konstgallerier": {},
        "Konstnärsmaterial": {},
        "Kontaktlinser": {},
        "Kosmetika": {},
        "Kryddor": {},
        "Köksartiklar": {},
        "Köpcentrum & Gallerior": {},
        "Kött-, slakteriprodukter": {},
        "Leksaker": {},
        "Leksaks-, Spel- & Hobbybutiker": {},
        "Lim, limämnen": {},
        "Livsmedelsbutiker": {},
        "Ljud & Bild": {},
        "Loppmarknader": {},
        "Lotteriservice": {},
        "Läkemedelsinformation": {},
        "Läromedel": {},
        "Mammakläder": {},
        "Maskeradartiklar": {},
        "Matbutiker": {},
        "Matkassar": {},
        "Mattaffärer": {},
        "Mobilreparation": {},
        "Mobiltelefoner": {},
        "Mopedförsäljning & Mopedverkstäder": {},
        "Musik - distribution": {},
        "Musik - skivbutiker": {},
        "Musikaffärer": {},
        "Musikinstrument, -tillbehör": {},
        "Musikinstrument, -tillbehör - reparationer": {},
        "Mynthandlare": {},
        "Målerikonsulter": {},
        "Måleriutrustning": {},
        "Möbelaffärer": {},
        "Möbeldelar, - tillbehör": {},
        "Möbelsnickare": {},
        "Navigationsutrustningar, -system": {},
        "Nätbutiker": {},
        "Optiker": {},
        "Outlet, fabriksförsäljning": {},
        "Packningar, tätningar": {},
        "Pantbanker": {},
        "Pappershandel": {},
        "Paraplyer": {},
        "Parfymerier": {},
        "Pianon, orglar": {},
        "Pianostämmare": {},
        "Porslinsmålning": {},
        "Post, postombud": {},
        "Postens Frimärksombud": {},
        "Postens Företagscenter": {},
        "Postens Postombud": {},
        "Postorder": {},
        "Postservice": {},
        "Profilkläder": {},
        "Pälsar & Skinnkläder": {},
        "Radio, tv - service": {},
        "Rep, linor": {},
        "Saluhallar": {},
        "Second Hand": {},
        "Sex & Erotik": {},
        "Silversmeder": {},
        "Sjukvårdsartiklar": {},
        "Sjömackar": {},
        "Skidor, snowboard": {},
        "Skoaffärer": {},
        "Skomakerier": {},
        "Skrädderier": {},
        "Slipsar": {},
        "Smycken": {},
        "Smörgåsaffärer": {},
        "Snickeri-, träförädlingsalster": {},
        "Spel & Lotterier": {},
        "Spelautomater, rouletter": {},
        "Spelcenter, laserspel": {},
        "Spelhallar": {},
        "Spelombud, spelbolag": {},
        "Spisar - kakelugnar, vedspisar, öppna spisar": {},
        "Sportaffärer & Friluftsutrustning": {},
        "Sportfiske": {},
        "Stearinljus": {},
        "Stegar": {},
        "Stickmaskiner": {},
        "Storhushållsvaror": {},
        "Stormarknader": {},
        "Strumpor": {},
        "Syateljéer": {},
        "Symaskiner": {},
        "Systembolag & Ombud": {},
        "Sängbutiker": {},
        "Tavlor & Ramar": {},
        "Tidningsaffärer & Tobaksaffärer": {},
        "Toaletter, hygienanläggningar": {},
        "Torkutrustningar": {},
        "Trädgårdar, plantskolor": {},
        "Trädgårdsbutiker": {},
        "Trädgårdsmöbler": {},
        "Trävaror": {},
        "TV- & Dataspel": {},
        "Tvättmaskiner, utrustningar": {},
        "Tyger": {},
        "Tält": {},
        "Ugnar": {},
        "Underkläder": {},
        "Vapen, ammunition - utrustningar": {},
        "Varuhus": {},
        "Video, dvd-film - försäljning, uthyrning": {},
        "Vitvarubutiker": {},
        "Väskor": {},
        "Växthus": {},
        "Yrkeskläder": {},
        "Zooaffärer": {},
        "Zoologiska artiklar - tillverkare, grossister": {}
    },
    "Bygg & Byggmaterial": {
        "Arbetarskyddsmaterial": {},
        "Arbetskläder": {},
        "Arkitekter": {},
        "Asfalt, asfaltbeläggningar": {},
        "Avfallshanteringsmaskiner, utrustningar": {},
        "Avloppsspolning": {},
        "Badrumsinredningar": {},
        "Badrumsrenoveringar": {},
        "Balkonger & Balkonginstallationer": {},
        "Balkonginglasning": {},
        "Bastuanläggningar, aggregat": {},
        "Bergsprängning, sprängning": {},
        "Beslag": {},
        "Betongvaror & Cement": {},
        "Bevattningsanläggningar": {},
        "Borstar, penslar": {},
        "Bostadsföretag": {},
        "Butiksmaskiner": {},
        "Bygg- & Anläggningsarbeten": {},
        "Bygg-, arbetsmaskiner": {},
        "Byggföretag": {},
        "Byggmaskiner & Byggverktyg": {},
        "Byggmästare & Byggnadsentreprenörer": {},
        "Byggnadssnickerier": {},
        "Byggnadsställningar": {},
        "Byggprojektering & Byggkonstruktion": {},
        "Byggvaror & Järnaffärer": {},
        "Byggvaruhus": {},
        "Charkuterimaskiner, tillbehör": {},
        "Dekorationsmaterial": {},
        "Dekorationsmålare": {},
        "Dikteringsmaskiner": {},
        "Dörrar & Portar": {},
        "Elartiklar": {},
        "Elektriker": {},
        "Elinstallation": {},
        "Entreprenad": {},
        "Entreprenadmaskiner - tillbehör, reservdelar": {},
        "Entreprenadmaskinsarbeten": {},
        "Fanér": {},
        "Fasadbehandling": {},
        "Fastighetsbolag": {},
        "Fastighetsförvaltning": {},
        "Fastighetsskötsel": {},
        "Fastighetsutveckling": {},
        "Filter": {},
        "Flaggor, flaggstänger": {},
        "Fläktar": {},
        "Fog-, tätningsentreprenörer": {},
        "Fontäner, dammar och vattenspel": {},
        "Fritidshus, friggebodar": {},
        "Färg & Tapeter": {},
        "Färganalys": {},
        "Fönsterrenoveringar": {},
        "Fönstertätning": {},
        "Förpackningsmaskiner": {},
        "Garageportar": {},
        "Gjuterier": {},
        "Glas & Fönster": {},
        "Glasmästerier": {},
        "Glassliperier": {},
        "Glassmaskiner, utrustning": {},
        "Golvbeläggningar": {},
        "Golvbutiker": {},
        "Golvläggare": {},
        "Golvslipning": {},
        "Golvvärme": {},
        "Golvvård": {},
        "Grundläggningsarbeten": {},
        "Gummi- & Plastvaruindustrier": {},
        "Gummivaror": {},
        "Hissar & Rulltrappor": {},
        "Husarkitekter": {},
        "Husrivningar": {},
        "Hustillverkare": {},
        "Hydraulik": {},
        "Högtrycksutrustningar": {},
        "Ingenjörer - akustik": {},
        "Ingenjörer - byggnadsteknik, samhällsplanering": {},
        "Ingenjörer - mätteknik": {},
        "Innemiljö": {},
        "Inredning - offentlig miljö": {},
        "Inredningar, renoveringar": {},
        "Inredningsarkitekter": {},
        "Isolering": {},
        "Isoleringsentreprenörer": {},
        "Järn, stål": {},
        "Järnvaror": {},
        "Kakel & Klinkers": {},
        "Kakelugnar & Kaminer": {},
        "Kakelugnsmakare": {},
        "Kemikalieindustrier & Kemiska produkter": {},
        "Kemikalier": {},
        "Kemisk rengöring": {},
        "Kemisk-tekniska varor": {},
        "Keramik - färdigprodukter": {},
        "Keramik - råmaterial, verktyg, maskiner": {},
        "Köksinredningar": {},
        "Köksrenoveringar": {},
        "Kökssnickerier": {},
        "Landskaps- & Trädgårdsarkitekter": {},
        "Lim, limämnen": {},
        "Lokaler, kontor - förmedling, uthyrning": {},
        "Mark- & Anläggningsentreprenader": {},
        "Maskinbrodyr": {},
        "Maskiner, maskinverktyg": {},
        "Maskinindustrier": {},
        "Maskinringar": {},
        "Maskinstationer": {},
        "Mattor - inläggningar, reparationer": {},
        "Modulbyggnader": {},
        "Muddringsarbeten": {},
        "Murare & Stensättare": {},
        "Målare": {},
        "Målerikonsulter": {},
        "Måleriutrustning": {},
        "Möbler - reparationer": {},
        "Packningar, tätningar": {},
        "Pappersindustrimaskiner": {},
        "Plast-, gummiindustrimaskiner": {},
        "Plaster - helfabrikat, beställningsarbeten": {},
        "Plaster - råvaror, halvfabrikat": {},
        "Plattsättning, plattor": {},
        "Plåt": {},
        "Plåtslagerier": {},
        "Presenningar & Kapell": {},
        "Profilkläder": {},
        "Pumpar & Pumputrustning": {},
        "Påsar, bärkassar, säckar": {},
        "Rep, linor": {},
        "Ritningar": {},
        "Rivningsarbeten": {},
        "Robotar": {},
        "Salt, spridningsutrustningar": {},
        "Skorstensbyggare, reparatörer": {},
        "Skumplast": {},
        "Slip-, polermaterial": {},
        "Smörjutrustningar": {},
        "Snickare": {},
        "Snickeri-, träförädlingsalster": {},
        "Snickeriarbeten": {},
        "Solvärme & Vindkraft": {},
        "Sotare": {},
        "Stegar": {},
        "Sten & Stenhuggerier": {},
        "Sten, stenarbeten": {},
        "Streckkoder, utrustningar": {},
        "Stuckatur-, gipsarbeten": {},
        "Svets-, skärutrustningar": {},
        "Symaskiner - tillverkare, grossister": {},
        "Sågar, sågblad, -verktyg": {},
        "Sågverk": {},
        "Takarbeten": {},
        "Takbeläggningar": {},
        "Takentreprenörer & Takläggare": {},
        "Tapetserare": {},
        "Tegel & Takpannor": {},
        "Tejper": {},
        "Toaletter, hygienanläggningar": {},
        "Trappor": {},
        "Tryckluftsutrustningar": {},
        "Trädgårdsmaskiner & Trädgårdsredskap": {},
        "Trävaror": {},
        "Uterum": {},
        "Vatten-, fuktskador": {},
        "Ventilation": {},
        "Ventiler, kopplingar": {},
        "Verkstadsutrustning": {},
        "Verktyg": {},
        "VVS & Rörmokare": {},
        "Värmebehandling": {},
        "Värmepumpar & Värmeväxlare": {},
        "Yrkeskläder": {},
        "Ång-, hetvattenpannor": {},
        "Åskskydd": {}
    },
    "Ekonomi & Juridik": {
        "Advokater": {},
        "Arbetsgivarorganisationer": {},
        "Arbetslöshetskassor": {},
        "Banker": {},
        "Bostadsrättsbildare, bostadsrättsförvaltare": {},
        "Bostadsrättsföreningar": {},
        "Bouppteckningar": {},
        "Bransch- & Yrkesorganisationer": {},
        "Domstolar": {},
        "Domstolsväsendet": {},
        "Finans- & Bankverksamhet": {},
        "Finansbolag": {},
        "Fond-, Kapitalförvaltning & Värdepapper": {},
        "Försäkrings- & Arbetslöshetskassa": {},
        "Investmentbolag & Riskkapitalbolag": {},
        "Juridiska byråer": {},
        "Jurister": {},
        "Kreditkort, betalkort, id-kort": {},
        "Kreditupplysningar & Inkasso": {},
        "Leasingbolag": {},
        "Pantbanker": {},
        "Patentbyråer": {},
        "Redovisning, Revision & Skatterådgivning": {},
        "Redovisningskonsulter - auktoriserade och övriga": {},
        "Revisorer - auktoriserade": {},
        "Revisorer - godkända": {},
        "Revisorer - övriga": {},
        "Skatte-, finanskonsulter": {},
        "Stiftelser & Fonder": {},
        "Svensk Kassaservice": {},
        "Värdepappersinstitut": {},
        "Växlingskontor": {}
    },
    "Företagstjänster": {
        "Adressregister": {},
        "Advokater": {},
        "Affischer, konstreproduktioner": {},
        "Agenturer": {},
        "Animeringar": {},
        "Apputvecklare": {},
        "Arbetsgivarorganisationer": {},
        "Arbetsmiljö": {},
        "Artister & Artistförmedlingar": {},
        "Av-produktion, -utrustningar": {},
        "Avfallshantering, renhållningsentreprenörer": {},
        "Banker": {},
        "Besiktningsman": {},
        "Bildbyråer": {},
        "Biljettförsäljning": {},
        "Biljettombud": {},
        "Bouppteckningar": {},
        "Bransch- & Yrkesorganisationer": {},
        "Bud & Kurir": {},
        "Budservice": {},
        "Butiksmarknadsföring": {},
        "Butiksutrustning, -förbrukningsvaror": {},
        "Båtlinjer, färjelinjer": {},
        "Båttransporter": {},
        "Callcenter, telefonpassning": {},
        "Catering": {},
        "Charter- & Taxiflyg": {},
        "Coachning, mentorskap": {},
        "Containrar": {},
        "Copywriters": {},
        "Data-, it-konsulter": {},
        "Design, formgivning": {},
        "Designbyråer": {},
        "Destruktionstjänster": {},
        "Direktmarknadsföring & Direktreklam": {},
        "Distribution": {},
        "Ergonomi": {},
        "Etiketter & Etikettryckerier": {},
        "Evenemang, eventbyråer": {},
        "Eventarrangörer": {},
        "Export, import": {},
        "Expresstransporter": {},
        "Faktureringstjänster": {},
        "Fest- & Samlingslokaler": {},
        "Festarrangörer": {},
        "Film- & Musikproduktion": {},
        "Finansbolag": {},
        "Flygtransporter": {},
        "Flyttstädning": {},
        "Fond-, Kapitalförvaltning & Värdepapper": {},
        "Formgivning": {},
        "Forskning & Utveckling": {},
        "Frö, utsäde": {},
        "Färjetrafik & Rederier": {},
        "Föreläsare, talarförmedlingar": {},
        "Företagsförmedling": {},
        "Företagshälsovård": {},
        "Företagsparker": {},
        "Företagsprofilering": {},
        "Företagsutveckling, -rekonstruktion": {},
        "Författare": {},
        "Försäkringar": {},
        "Försäkringsbolag & Försäkringsförmedling": {},
        "Godsterminaler": {},
        "Grafisk verksamhet": {},
        "Grafiskt material och utrustning": {},
        "Handikapptransporter": {},
        "Hushållsnära tjänster, hemservice": {},
        "Högtryckstvättning": {},
        "Impregnering": {},
        "Inbrottsskydd": {},
        "Industrikonsulter": {},
        "Infartsparkeringar": {},
        "Information, public relations": {},
        "Informationstjänster": {},
        "Investmentbolag & Riskkapitalbolag": {},
        "IT - Konsult & Drift": {},
        "Journalister & Reportage": {},
        "Juridiska byråer": {},
        "Jurister": {},
        "Kaffeautomater": {},
        "Kalibrering": {},
        "Kartor, geografiska informationssystem": {},
        "Kassaregister, butiksdata": {},
        "Kassaservice": {},
        "Konferens- & Mässarrangörer": {},
        "Konferensanläggningar & Kursgårdar": {},
        "Konferenser & Mässor": {},
        "Konferenslokaler": {},
        "Konferensutrustning": {},
        "Kongressarrangörer": {},
        "Konstnärer & Illustratörer": {},
        "Konstnärsmaterial": {},
        "Kontorsinredningar": {},
        "Kontorsmaskiner": {},
        "Kontorsmaterial": {},
        "Kontorsmoduler": {},
        "Kontorsservicetjänster": {},
        "Kopiering": {},
        "Kopieringsutrustning, materiel": {},
        "Kreaturshandel": {},
        "Kreditkort, betalkort, id-kort": {},
        "Kreditupplysningar & Inkasso": {},
        "Kursgårdar": {},
        "Kuvert & Kuverttryckerier": {},
        "Laboratorier & Laboratorieutrustningar": {},
        "Lager-, förrådsinredningar": {},
        "Lantmäteritjänster": {},
        "Larm & Bevakning": {},
        "Larmcentraler": {},
        "Lastkajer, dockningsanläggningar": {},
        "Lastpallar, lastmaterial": {},
        "Leasingbolag": {},
        "Lekplats-, parkutrustning": {},
        "Leksaker, lekredskap - tillverkare, grossister": {},
        "Ljudinspelning": {},
        "Logistik": {},
        "Lyftanordningar": {},
        "Magasinering": {},
        "Managementkonsulter": {},
        "Marknadsföringskonsulter": {},
        "Marknadsundersökningar": {},
        "Maskiner, maskinverktyg - uthyrning": {},
        "Maskinuthyrning": {},
        "Mat- & Dryckesautomater": {},
        "Mediabyråer": {},
        "Mediaproduktion": {},
        "Medieförmedling, -försäljning": {},
        "Miljökonsulter": {},
        "Miljöledningssystem": {},
        "Multimedia - produktioner": {},
        "Märksystem - utrustningar": {},
        "Mäss-, utställningsproduktion": {},
        "Mönsterkort": {},
        "Namnbyråer": {},
        "Nyhetsbyråer": {},
        "Nyhetsservice": {},
        "Oljesanering, -utrustning": {},
        "Oljesanering, tankrengöring": {},
        "Omvärldsbevakning": {},
        "Ordningsvakter": {},
        "Organisationskonsulter": {},
        "Pappershandel": {},
        "Parkeringsbolag, -utrustning": {},
        "Parkeringshus, parkeringar": {},
        "Parkeringsservice": {},
        "Partihandel": {},
        "Passersystem": {},
        "Patentbyråer": {},
        "Pensionsrådgivning": {},
        "Personal-, kompetensutveckling": {},
        "Personalutbildningar": {},
        "Personlig utveckling": {},
        "Postservice": {},
        "PR-byråer": {},
        "Prepressarbeten": {},
        "Presentartiklar": {},
        "Presentreklam": {},
        "Profil & Reklamartiklar": {},
        "Radio - inspelning, produktion, reklam": {},
        "Radiobolag, -stationer": {},
        "Redovisning, Revision & Skatterådgivning": {},
        "Redovisningskonsulter - auktoriserade och övriga": {},
        "Reklam & PR": {},
        "Reklam- & Annonsbyråer": {},
        "Reklamateljéer": {},
        "Rengöringsprodukter": {},
        "Reproarbeten": {},
        "Restaurangutrustning, storköksutrustning, -konsulter": {},
        "Returpapper": {},
        "Revisorer - auktoriserade": {},
        "Revisorer - godkända": {},
        "Revisorer - övriga": {},
        "Sanering": {},
        "Scenografi, teaterdekor": {},
        "Screen- & Textiltryckerier": {},
        "Skatte-, finanskonsulter": {},
        "Skrivbyråer": {},
        "Skyddsrum, skyddsrumsmaterial": {},
        "Skyltar & Utställningsmaterial": {},
        "Skyltdockor": {},
        "Skyltställ": {},
        "Spedition & Transport": {},
        "Språkgranskning, -redigering": {},
        "Stiftelser & Fonder": {},
        "Stuverier": {},
        "Städning & Rengöring": {},
        "Städservice, industriell rengöring": {},
        "Städutrustning": {},
        "Säkerhet - system, utrustning": {},
        "Säkerhetskonsulter": {},
        "Säkerhetsrådgivare": {},
        "Sättningsarbeten": {},
        "Sökmotoroptimering": {},
        "Taxi": {},
        "Teknik - Konsulter & Analyser": {},
        "Teknikkonsulter": {},
        "Telemarketing & Callcenter": {},
        "Tolkar - auktoriserade": {},
        "Tolkservice & Översättningar": {},
        "Truckar, truckkomponenter": {},
        "Tryckeri-, bokbinderiutrustning": {},
        "Tryckerier & Bokbinderier": {},
        "Uppfinnare": {},
        "Utomhusreklam": {},
        "Utrymningssystem": {},
        "Värdepappersinstitut": {},
        "Värdetransporter": {},
        "Webbhotell, serverhotell": {},
        "Webbyråer": {},
        "Åkerier": {},
        "Återvinning": {},
        "Återvinningscentral": {}
    },
    "Hus & Hem": {
        "Antikvariat": {},
        "Antikviteter": {},
        "Arkitekter": {},
        "Armaturfabriker": {},
        "Asfalt, asfaltbeläggningar": {},
        "Auktioner": {},
        "Avfallshantering, renhållningsentreprenörer": {},
        "Avloppsspolning": {},
        "Badrumsinredningar": {},
        "Badrumsrenoveringar": {},
        "Balkonger & Balkonginstallationer": {},
        "Balkonginglasning": {},
        "Bastuanläggningar, aggregat": {},
        "Belysningar & Lampaffärer": {},
        "Bergsprängning, sprängning": {},
        "Bergvärme": {},
        "Beslag": {},
        "Betonghåltagning": {},
        "Betongvaror & Cement": {},
        "Bevattningsanläggningar": {},
        "Biobränsle": {},
        "Blommor": {},
        "Blomsterhandel": {},
        "Borrning": {},
        "Borstar, penslar": {},
        "Bostadsföretag": {},
        "Bostadsförmedlingar": {},
        "Bostadsrättsbildare, bostadsrättsförvaltare": {},
        "Bostadsrättsföreningar": {},
        "Brunnsborrning & Borrarbeten": {},
        "Butiksinredningar": {},
        "Bygg- & Anläggningsarbeten": {},
        "Bygg-, arbetsmaskiner": {},
        "Byggföretag": {},
        "Byggmaskiner & Byggverktyg": {},
        "Byggmästare & Byggnadsentreprenörer": {},
        "Byggnadssnickerier": {},
        "Byggnadsställningar": {},
        "Byggvaror & Järnaffärer": {},
        "Byggvaruhus": {},
        "Bärhandel, odlare": {},
        "Dammsugare": {},
        "Dekorationsmaterial": {},
        "Dekorationsmålare": {},
        "Destruktionstjänster": {},
        "Diamantverktyg": {},
        "Diskmaskiner": {},
        "Dörrar & Portar": {},
        "Elartiklar": {},
        "Eldistribution": {},
        "Eldningsolja": {},
        "Elektriker": {},
        "Elförsäljning": {},
        "Elinstallation": {},
        "Energibesparing, - effektivisering": {},
        "Energideklarering": {},
        "Energiförsäljning, energiproduktion, energimäklare": {},
        "Energikonsult": {},
        "Entreprenad": {},
        "Entreprenadmaskiner - tillbehör, reservdelar": {},
        "Entreprenadmaskinsarbeten": {},
        "Fanér": {},
        "Fasadbehandling": {},
        "Fastigheter - utlandet": {},
        "Fastighetsbesiktningar": {},
        "Fastighetsbolag": {},
        "Fastighetsförvaltning": {},
        "Fastighetsmäklare": {},
        "Fastighetsmäklare - Utland": {},
        "Fastighetsskötsel": {},
        "Fastighetsutveckling": {},
        "Fastighetsvärderingar": {},
        "Filter": {},
        "Flaggor, flaggstänger": {},
        "Flyttfirmor": {},
        "Flyttstädning": {},
        "Fläktar": {},
        "Fog-, tätningsentreprenörer": {},
        "Fontäner, dammar och vattenspel": {},
        "Fritidshus, friggebodar": {},
        "Frukt-, Bär- & Grönsaksodlingar": {},
        "Fruktleverantörer": {},
        "Färg & Tapeter": {},
        "Färganalys": {},
        "Fästelement": {},
        "Fönsterputsning": {},
        "Fönsterrenoveringar": {},
        "Fönstertätning": {},
        "Försäkringar": {},
        "Försäkringsbolag & Försäkringsförmedling": {},
        "Garageportar": {},
        "Garderober": {},
        "Garner, Tyger & Sybehör": {},
        "Gatumöbler, utrustning": {},
        "Gaturenhållning, Avlopps- & Avfallshantering": {},
        "Glas & Fönster": {},
        "Glas & Porslin": {},
        "Glasbruk": {},
        "Glasmästerier": {},
        "Glasmåleri, konstglasmästeri": {},
        "Glassliperier": {},
        "Golvbeläggningar": {},
        "Golvbutiker": {},
        "Golvläggare": {},
        "Golvslipning": {},
        "Golvvärme": {},
        "Golvvård": {},
        "Gravyr": {},
        "Gravörer": {},
        "Grundläggningsarbeten": {},
        "Gräsmattor": {},
        "Gödsel": {},
        "Handarbeten": {},
        "Handelsträdgårdar": {},
        "Hantverk & Hemslöjd": {},
        "Hemelektronik & Hushållsapparater": {},
        "Heminredning": {},
        "Hemtextilier & Gardiner": {},
        "Hissar & Rulltrappor": {},
        "Homestaging": {},
        "Husarkitekter": {},
        "Hushållsapparatservice": {},
        "Hushållsartiklar": {},
        "Hushållsnära tjänster, hemservice": {},
        "Hushållsutrustning, vitvaror": {},
        "Husrivningar": {},
        "Hustillverkare": {},
        "Hyllor, hyllsystem": {},
        "Högtryckstvättning": {},
        "Högtrycksutrustningar": {},
        "Inbrottsskydd": {},
        "Innemiljö": {},
        "Inredning - offentlig miljö": {},
        "Inredningar, renoveringar": {},
        "Inredningsarkitekter": {},
        "Inredningsartiklar": {},
        "Is, ismaskiner": {},
        "Isolering": {},
        "Isoleringsentreprenörer": {},
        "Jordleverantörer": {},
        "Järn, stål": {},
        "Järnvaror": {},
        "Kakel & Klinkers": {},
        "Kakelugnar & Kaminer": {},
        "Kakelugnsmakare": {},
        "Kassaskåp": {},
        "Kompostering, utrustning": {},
        "Konservatorer": {},
        "Konst, konsthantverk": {},
        "Kontorsinredningar": {},
        "Kontorsmaskiner": {},
        "Kontorsmaterial": {},
        "Kyl- & Frysanläggningar": {},
        "Kylare": {},
        "Köksartiklar": {},
        "Köksinredningar": {},
        "Köksrenoveringar": {},
        "Kökssnickerier": {},
        "Lager-, förrådsinredningar": {},
        "Landskaps- & Trädgårdsarkitekter": {},
        "Larm & Bevakning": {},
        "Larmcentraler": {},
        "Lim, limämnen": {},
        "Lokaler, kontor - förmedling, uthyrning": {},
        "Lås- & Nyckelservice": {},
        "Magasinering": {},
        "Mark- & Anläggningsentreprenader": {},
        "Markiser & Persienner": {},
        "Mattaffärer": {},
        "Mattor - inläggningar, reparationer": {},
        "Modulbyggnader": {},
        "Muddringsarbeten": {},
        "Murare & Stensättare": {},
        "Mynthandlare": {},
        "Märksystem - utrustningar": {},
        "Målare": {},
        "Målerikonsulter": {},
        "Måleriutrustning": {},
        "Möbelaffärer": {},
        "Möbeldelar, - tillbehör": {},
        "Möbelindustrier": {},
        "Möbelsnickare": {},
        "Möbelstoppningsmaterial": {},
        "Möbler - reparationer": {},
        "Möbler - tillverkare, grossister": {},
        "Navigationsutrustningar, -system": {},
        "Oljeeldning - anläggningar, tillbehör": {},
        "Oljeeldning - installationer, service": {},
        "Oljesanering, -utrustning": {},
        "Oljesanering, tankrengöring": {},
        "Oljor, oljeprodukter": {},
        "Ordningsvakter": {},
        "Packningar, tätningar": {},
        "Passersystem": {},
        "Pelletsvärme, pellets": {},
        "Pensionsrådgivning": {},
        "Plattsättning, plattor": {},
        "Plåt": {},
        "Plåtslagerier": {},
        "Pooler & Spabad": {},
        "Porslinsmålning": {},
        "Presenningar & Kapell": {},
        "Pumpar & Pumputrustning": {},
        "Rengöringsprodukter": {},
        "Renhållning, soputrustningar": {},
        "Rep, linor": {},
        "Reservkraft": {},
        "Returpapper": {},
        "Ritningar": {},
        "Rivningsarbeten": {},
        "Rumsuthyrning": {},
        "Sanering": {},
        "Skorstensbyggare, reparatörer": {},
        "Skyddsrum, skyddsrumsmaterial": {},
        "Slamsugning": {},
        "Snickare": {},
        "Snickeri-, träförädlingsalster": {},
        "Snickeriarbeten": {},
        "Solfångare": {},
        "Solskydd": {},
        "Solvärme & Vindkraft": {},
        "Sotare": {},
        "Spisar - kakelugnar, vedspisar, öppna spisar": {},
        "Stadsbud": {},
        "Stearinljus": {},
        "Stegar": {},
        "Sten & Stenhuggerier": {},
        "Sten, stenarbeten": {},
        "Stickmaskiner": {},
        "Stubbfräsning": {},
        "Stuckatur-, gipsarbeten": {},
        "Städning & Rengöring": {},
        "Städservice, industriell rengöring": {},
        "Städutrustning": {},
        "Symaskiner": {},
        "Säkerhet - system, utrustning": {},
        "Sängbutiker": {},
        "Sågar, sågblad, -verktyg": {},
        "Sågverk": {},
        "Takarbeten": {},
        "Takbeläggningar": {},
        "Takentreprenörer & Takläggare": {},
        "Tapetserare": {},
        "Tegel & Takpannor": {},
        "Toaletter, hygienanläggningar": {},
        "Torkutrustningar": {},
        "Torv, torvströ, torvmull": {},
        "Trappor": {},
        "Trädfällning, trädvård": {},
        "Trädgårdar, plantskolor": {},
        "Trädgårdsanläggare": {},
        "Trädgårdsbutiker": {},
        "Trädgårdsmaskiner & Trädgårdsredskap": {},
        "Trädgårdsmaskinindustrier": {},
        "Trädgårdsmästare & Trädgårdsskötsel": {},
        "Trädgårdsmöbler": {},
        "Trävaror": {},
        "Tvätt & Kemtvätt": {},
        "Tvättmaskiner, utrustningar": {},
        "Tyger": {},
        "Ugnar": {},
        "Uterum": {},
        "Utrymningssystem": {},
        "Vatten-, fuktskador": {},
        "Vattenbehandling, vattenbehandlingsutrustning": {},
        "Vattenreningsutrustningar": {},
        "Ved, flis, kol": {},
        "Ventilation": {},
        "Ventiler, kopplingar": {},
        "Verktyg": {},
        "Villauppvärmning": {},
        "Vitvarubutiker": {},
        "VVS & Rörmokare": {},
        "Värderingar": {},
        "Värdetransporter": {},
        "Värmebehandling": {},
        "Värmepumpar & Värmeväxlare": {},
        "Värmeutrustningar": {},
        "Värmeverk": {},
        "Växthus": {},
        "Ång-, hetvattenpannor": {},
        "Åskskydd": {},
        "Återvinning": {},
        "Återvinningscentral": {}
    },
    "Hushållsnära tjänster": {
        "Barnpassning": {},
        "Flyttstädning": {},
        "Fönsterputsning": {},
        "Gräsmattor": {},
        "Gödsel": {},
        "Hushållsnära tjänster, hemservice": {},
        "Personliga assistenter": {},
        "Rengöringsprodukter": {},
        "Snöskottning": {},
        "Stubbfräsning": {},
        "Städning & Rengöring": {},
        "Städservice, industriell rengöring": {},
        "Städutrustning": {},
        "Trädfällning, trädvård": {},
        "Trädgårdsanläggare": {},
        "Trädgårdsmästare & Trädgårdsskötsel": {},
        "Tvätt & Kemtvätt": {}
    },
    "Hälsa & Skönhet": {
        "Akupunktur & Akupressur": {},
        "Allergiläkare & Lungspecialister": {},
        "Allmänläkare": {},
        "Alternativmedicin": {},
        "Ambulans & Sjuktransport": {},
        "Apotek": {},
        "Apoteksombud": {},
        "Arbetsmiljö": {},
        "Badplats": {},
        "Barnavårdscentraler": {},
        "Barnläkare": {},
        "Bioteknik, medicinteknik": {},
        "Budosporter": {},
        "Curling - hallar, banor": {},
        "Dietister": {},
        "Distriktssköterskor": {},
        "Elektromedicinsk utrustning": {},
        "Ergonomi": {},
        "Familjecentraler": {},
        "Familjerådgivning": {},
        "Fotvård": {},
        "Frisk-, hälsovård": {},
        "Frisörer": {},
        "Frisörutrustningar": {},
        "Fysioterapeut": {},
        "Företagshälsovård": {},
        "Gym & Motion": {},
        "Gynekologer & Förlossningsläkare": {},
        "Handikappsutrustningar": {},
        "Healing": {},
        "Hemsjukvård": {},
        "Homeopater": {},
        "Hudläkare & Könssjukdomar": {},
        "Hudvård": {},
        "Husläkare": {},
        "Hypnos": {},
        "Hälsokost": {},
        "Hälsorådgivning": {},
        "Hårvårdsprodukter": {},
        "Hörselhjälpmedel, hörapparater": {},
        "Ideella föreningar, samhällstjänster": {},
        "Idrottsföreningar & Idrottsförbund": {},
        "Kardiologer & Hjärtspecialister": {},
        "Kiropraktorer": {},
        "Kirurger": {},
        "Kontaktlinser": {},
        "Kosmetika": {},
        "Kosttillskott - tillverkare, grossister": {},
        "Kroppsterapeuter": {},
        "Laserbehandling, -kliniker": {},
        "Läkare": {},
        "Läkare - hälsokontroller, vaccinationer": {},
        "Läkare: spec. kompetens": {},
        "Läkare: spec. kompetens - allmänmedicin": {},
        "Läkare: spec. kompetens - anestesi, intensivvård": {},
        "Läkare: spec. kompetens - endokrinologi, hormonrubbningar": {},
        "Läkare: spec. kompetens - gastroenterologi, mag-, tarmsjukdomar": {},
        "Läkare: spec. kompetens - geriatrik, äldrevård": {},
        "Läkare: spec. kompetens - gynekologisk onkologi, tumörsjukdomar": {},
        "Läkare: spec. kompetens - hörselrubbningar": {},
        "Läkare: spec. kompetens - infektionssjukdomar": {},
        "Läkare: spec. kompetens - internmedicin": {},
        "Läkare: spec. kompetens - klinisk neurofysiologi": {},
        "Läkare: spec. kompetens - klinisk näringslära": {},
        "Läkare: spec. kompetens - neurologi": {},
        "Läkare: spec. kompetens - njursjukdomar": {},
        "Läkare: spec. kompetens - onkologi, tumörsjukdomar": {},
        "Läkare: spec. kompetens - ortopedi": {},
        "Läkare: spec. kompetens - radiologi, röntgendiagnostik": {},
        "Läkare: spec. kompetens - reumatologi": {},
        "Läkare: spec. kompetens - smärtlindring": {},
        "Läkare: spec. kompetens - ögonsjukdomar": {},
        "Läkare: spec. kompetens - öron-, näs-, halssjukdomar": {},
        "Läkemedel": {},
        "Läkemedelsindustrier": {},
        "Läkemedelsinformation": {},
        "Massage": {},
        "Massörer": {},
        "Medicinska Utrustningar": {},
        "Motionsanläggningar, friluftsgårdar": {},
        "Mödravård, barnmorskor, preventivmedelsrådgivning": {},
        "Mödravårdscentraler": {},
        "Nagelvård": {},
        "Naprapater": {},
        "Neurologer": {},
        "Optiker": {},
        "Osteopater": {},
        "Parfymerier": {},
        "Peruker, löshår": {},
        "Plastikkirurger": {},
        "Psykiatriker": {},
        "Psykologer": {},
        "Psykoterapeuter": {},
        "Rackethallar": {},
        "Rehabilitering, habilitering": {},
        "Rosenterapeuter": {},
        "Samtalsterapeuter, samtalsbehandlare": {},
        "Sex-, samlevnadsrådgivning": {},
        "Simhallar & Utomhusbad": {},
        "Simskolor": {},
        "Sjukgymnaster": {},
        "Sjukhus & Lasarett": {},
        "Sjuksköterskor - legitimerade": {},
        "Sjukvård": {},
        "Sjukvårdsartiklar": {},
        "Sjukvårdsrådgivning": {},
        "Sjukvårdsupplysningar": {},
        "Skönhetsbehandlingar": {},
        "Social rådgivning": {},
        "Solarieutrustning": {},
        "Solarium": {},
        "SPA-anläggningar": {},
        "Specialistläkare": {},
        "Specialisttandläkare": {},
        "Sport- & Idrottsanläggningar": {},
        "Tai chi": {},
        "Tandhygienister": {},
        "Tandläkare": {},
        "Tatueringar & Piercingar": {},
        "Tennisklubbar & Tennisbanor": {},
        "Ungdomsmottagning & Preventivmedelsrådgivning": {},
        "Urologer": {},
        "Vårdcentraler": {},
        "Yoga & Meditation": {},
        "Zonterapi & Reflexologi": {},
        "Ögonläkare": {},
        "Öppen Hälso- & Sjukvård": {},
        "Öron- Näsa- & Halsläkare": {}
    },
    "Industri & Transport": {
        "Aluminium, aluminiumprodukter": {},
        "Avfallshanteringsmaskiner, utrustningar": {},
        "Bevattningsanläggningar": {},
        "Biobränsle": {},
        "Bioteknik, medicinteknik": {},
        "Blästring, utrustningar": {},
        "Bryggerier, Vin- & Spritproducenter": {},
        "Bränsleindustrier": {},
        "Bud & Kurir": {},
        "Budservice": {},
        "Bussar - Linjetrafik & Expressbussar": {},
        "Bussbolag": {},
        "Bussresearrangörer & Bussuthyrning": {},
        "Butiksmaskiner": {},
        "Byggmaskiner & Byggverktyg": {},
        "Båtlinjer, färjelinjer": {},
        "Båttransporter": {},
        "Charkuterimaskiner, tillbehör": {},
        "Charter- & Taxiflyg": {},
        "Containrar": {},
        "Dikteringsmaskiner": {},
        "Distribution": {},
        "Dryckesvaruindustrier": {},
        "Elautomation": {},
        "Elektromedicinsk utrustning": {},
        "Elektromekaniska verkstäder": {},
        "Elektronik- & Optikindustrier": {},
        "Entreprenadmaskiner - tillbehör, reservdelar": {},
        "Export, import": {},
        "Expresstransporter": {},
        "Fisk, skaldjur - grossister": {},
        "Fjäderfä - kläckerier, uppfödning": {},
        "Flygbolag": {},
        "Flygplatser": {},
        "Flygtransporter": {},
        "Flyttfirmor": {},
        "Form-, pressverktyg": {},
        "Forskning & Utveckling": {},
        "Färjetrafik & Rederier": {},
        "Förpackningsmaskiner": {},
        "Förpackningstjänster": {},
        "Gallerdurk": {},
        "Gas - anläggning, tillbehör": {},
        "Geotextil": {},
        "Glasbruk": {},
        "Glasmåleri, konstglasmästeri": {},
        "Glassmaskiner, utrustning": {},
        "Godsterminaler": {},
        "Gravyrmaskiner": {},
        "Grus, sand, singel, makadam": {},
        "Gummi- & Plastvaruindustrier": {},
        "Gummivaror": {},
        "Handikappsutrustningar": {},
        "Hydraulik": {},
        "Industri för ickemetalliska mineraliska produkter": {},
        "Industriautomation": {},
        "Ingenjörer - elektronik": {},
        "Ingenjörer - elektroteknik": {},
        "Ingenjörer - maskinteknik, mek.konstruktioner": {},
        "Ingenjörer - optik": {},
        "Ingenjörer - processteknik": {},
        "Juice- & Saftindustrier": {},
        "Juicebarer": {},
        "Järnväg, spårväg - arbete, material": {},
        "Järnvägsstationer": {},
        "Kaffe- & Teindustrier": {},
        "Kafferosterier": {},
        "Kalkprodukter": {},
        "Kemikalieindustrier & Kemiska produkter": {},
        "Kemikalier": {},
        "Kemisk rengöring": {},
        "Kemisk-tekniska varor": {},
        "Keramik - färdigprodukter": {},
        "Keramik - råmaterial, verktyg, maskiner": {},
        "Kollektivtrafik": {},
        "Kontorsmaskin- & Datorindustrier": {},
        "Kullager": {},
        "Laboratorier & Laboratorieutrustningar": {},
        "Lant- & Jordbruk": {},
        "Lantbruksförnödenheter": {},
        "Laserarbeten, utrustningar": {},
        "Lastbilar, Bussar & Specialfordon": {},
        "Lastbilspåbyggnader": {},
        "Lastkajer, dockningsanläggningar": {},
        "Lastpallar, lastmaterial": {},
        "Legoarbeten": {},
        "Livräddningsutrustning": {},
        "Livsmedelsindustrier": {},
        "Livsmedelsindustrimaskiner": {},
        "Logistik": {},
        "Läder, skinn": {},
        "Läderindustrier & Textilindustrier": {},
        "Läkemedel": {},
        "Läkemedelsindustrier": {},
        "Lödning": {},
        "Malmer & Mineralindustrier": {},
        "Maskinbrodyr": {},
        "Maskiner, maskinverktyg": {},
        "Maskinhydraulik": {},
        "Maskinindustrier": {},
        "Maskinringar": {},
        "Maskinstationer": {},
        "Medicinska Utrustningar": {},
        "Mejerier": {},
        "Mekaniska Verkstäder": {},
        "Metall & Metallvaruindustrier": {},
        "Metallarbeten": {},
        "Metaller, legeringar": {},
        "Metallglaspartier": {},
        "Mineralvatten- & Läskedryckesindustrier": {},
        "Musterier": {},
        "Mät- & Precisionsutrustningar": {},
        "Möbelindustrier": {},
        "Möbelstoppningsmaterial": {},
        "Möbler - tillverkare, grossister": {},
        "Optik- & Urindustrier": {},
        "Optiska artiklar": {},
        "Organiska livsmedel": {},
        "Pappersbruk": {},
        "Pappersindustrimaskiner": {},
        "Plast-, gummiindustrimaskiner": {},
        "Plaster - helfabrikat, beställningsarbeten": {},
        "Plaster - råvaror, halvfabrikat": {},
        "Plywood": {},
        "Pumpar & Pumputrustning": {},
        "Påsar, bärkassar, säckar": {},
        "Radon, värmemätning": {},
        "Robotar": {},
        "Rökerier": {},
        "Salt, spridningsutrustningar": {},
        "Skogs- & Jordbruksmaskiner": {},
        "Skogsbruk & Skogsindustrier": {},
        "Skogstjänster": {},
        "Skumplast": {},
        "Slip-, polermaterial": {},
        "Sliperier": {},
        "Smidesverkstäder": {},
        "Smörjutrustningar": {},
        "Sockerbruk": {},
        "Spannmål, spannmålsprodukter": {},
        "Spedition & Transport": {},
        "Stadsbud": {},
        "Streckkoder, utrustningar": {},
        "Stuverier": {},
        "Styr-, reglerteknik": {},
        "Stängsel, stängselnät": {},
        "Stål-, metallinor, tråd, kätting": {},
        "Stålrör, stålprofiler": {},
        "Svarvning": {},
        "Svets-, skärutrustningar": {},
        "Svetsning": {},
        "Symaskiner - tillverkare, grossister": {},
        "Sågar, sågblad, -verktyg": {},
        "Sågverk": {},
        "Tejper": {},
        "Telefonmöten, telefonkonferenser, videokonferenser": {},
        "Telefonsystem": {},
        "Telekommunikation - installationer, utrustningar, system": {},
        "Telekomutrustningar": {},
        "Traktorer": {},
        "Transportmedelsindustrier": {},
        "Tryckluftsutrustningar": {},
        "Trä-, Massa- & Pappersindustrier": {},
        "Tåg- & Spårtrafik": {},
        "Tågresor - tågtransporter": {},
        "Verkstadsutrustning": {},
        "Verktyg": {},
        "Väverier, vävnader": {},
        "Vågar": {},
        "Ytbehandling": {},
        "Äggproduktion": {},
        "Åkerier": {},
        "Ölimportörer, -grossister": {},
        "Övriga tillverkningsindustrier": {}
    },
    "IT, Media & Elektronik": {
        "Adressregister": {},
        "Affischer, konstreproduktioner": {},
        "Animeringar": {},
        "Antenner": {},
        "Apputvecklare": {},
        "Av-produktion, -utrustningar": {},
        "Besiktningsman": {},
        "Bildbyråer": {},
        "Bokförlag": {},
        "Bredbandsleverantörer, -operatörer": {},
        "Butiksmarknadsföring": {},
        "Cad/cam-system": {},
        "Callcenter, telefonpassning": {},
        "CD & DVD": {},
        "Copywriters": {},
        "Data & IT": {},
        "Data - affärssystem": {},
        "Data - e-handelsprogram, system": {},
        "Data - finans-, handelssystem": {},
        "Data - system-, programutveckling": {},
        "Data-, it-konsulter": {},
        "Datakommunikation": {},
        "Datasäkerhet": {},
        "Datorer & Datortillbehör": {},
        "Datorer - installationer": {},
        "Datorgrafik": {},
        "Datorservice & Datorreparationer": {},
        "Design, formgivning": {},
        "Designbyråer": {},
        "Direktmarknadsföring & Direktreklam": {},
        "Dokumentationstjänster, -dokumenthantering": {},
        "Elektronik- & Optikindustrier": {},
        "Fiberoptik": {},
        "Film- & Musikproduktion": {},
        "Formgivning": {},
        "Fotoaffärer": {},
        "Fotografer": {},
        "Företagsprofilering": {},
        "Grafisk verksamhet": {},
        "Grafiskt material och utrustning": {},
        "Industriautomation": {},
        "Industrikonsulter": {},
        "Information, public relations": {},
        "Informationstjänster": {},
        "Ingenjörer - elektronik": {},
        "Ingenjörer - elektroteknik": {},
        "Ingenjörer - maskinteknik, mek.konstruktioner": {},
        "Ingenjörer - optik": {},
        "Ingenjörer - processteknik": {},
        "Internet-, intranätlösningar": {},
        "Ip-telefoni": {},
        "IT - Konsult & Drift": {},
        "IT-systemleverantörer & Applikationsleverantörer": {},
        "Journalister & Reportage": {},
        "Kabel-TV": {},
        "Kalibrering": {},
        "Kartor, geografiska informationssystem": {},
        "Kodlås, porttelefoner": {},
        "Kontorsmaskin- & Datorindustrier": {},
        "Korsord": {},
        "Lantmäteritjänster": {},
        "Laserarbeten, utrustningar": {},
        "Ljud & Bild": {},
        "Ljud- & Ljusanläggningar": {},
        "Ljudinspelning": {},
        "Ljusdesign, ljussättning": {},
        "Marknadsföringskonsulter": {},
        "Mediabyråer": {},
        "Mediaproduktion": {},
        "Medieförmedling, -försäljning": {},
        "Miljökonsulter": {},
        "Miljöledningssystem": {},
        "Mobilreparation": {},
        "Mobiltelefoner": {},
        "Multimedia - produktioner": {},
        "Mät- & Precisionsutrustningar": {},
        "Mönsterkort": {},
        "Namnbyråer": {},
        "Nyhetsbyråer": {},
        "Nyhetsservice": {},
        "Omvärldsbevakning": {},
        "Optik- & Urindustrier": {},
        "Optiska artiklar": {},
        "Postservice": {},
        "PR-byråer": {},
        "Prepressarbeten": {},
        "Presentartiklar": {},
        "Presentreklam": {},
        "Profil & Reklamartiklar": {},
        "Radio - inspelning, produktion, reklam": {},
        "Radio, tv - service": {},
        "Radiobolag, -stationer": {},
        "Radioproduktion": {},
        "Radon, värmemätning": {},
        "Reklam & PR": {},
        "Reklam- & Annonsbyråer": {},
        "Reklamateljéer": {},
        "Reproarbeten": {},
        "Skrivbyråer": {},
        "Skyltar & Utställningsmaterial": {},
        "Skyltdockor": {},
        "Skyltställ": {},
        "Styr-, reglerteknik": {},
        "Säkerhetskonsulter": {},
        "Säkerhetsrådgivare": {},
        "Sättningsarbeten": {},
        "Sökmotoroptimering": {},
        "Teknik - Konsulter & Analyser": {},
        "Teknikkonsulter": {},
        "Tele-, mobiloperatörer": {},
        "Telefon, fax, tillbehör": {},
        "Telefonmöten, telefonkonferenser, videokonferenser": {},
        "Telefonsystem": {},
        "Telekommunikation": {},
        "Telekommunikation - installationer, utrustningar, system": {},
        "Telekomutrustningar": {},
        "Telemarketing & Callcenter": {},
        "Tidningar & Tidskrifter": {},
        "Tryckeri-, bokbinderiutrustning": {},
        "Tryckerier & Bokbinderier": {},
        "TV-bolag": {},
        "Utomhusreklam": {},
        "Video, dvd-film - försäljning, uthyrning": {},
        "Webbhotell, serverhotell": {},
        "Webbyråer": {}
    },
    "Jobb & Utbildning": {
        "Arbetsförmedling": {},
        "Arbetsgivarorganisationer": {},
        "Arbetslöshetskassor": {},
        "Bemanningsföretag": {},
        "Bransch- & Yrkesorganisationer": {},
        "Coachning, mentorskap": {},
        "Daghem, Förskolor & Fritidshem": {},
        "Datautbildning": {},
        "Fackliga organisationer": {},
        "Folkhögskolor": {},
        "Fritidsgård": {},
        "Försäkrings- & Arbetslöshetskassa": {},
        "Grundskolor": {},
        "Gymnasium": {},
        "Högstadieskolor": {},
        "Komvux": {},
        "Kursverksamhet, studieförbund": {},
        "Outsourcing": {},
        "Personal-, kompetensutveckling": {},
        "Personalutbildningar": {},
        "Personlig utveckling": {},
        "Rekrytering & Personaluthyrning": {},
        "Sfi": {},
        "Språkutbildning": {},
        "Studentföreningar": {},
        "Studentorganisationer": {},
        "Särskola": {},
        "Trafikskolor": {},
        "Trafikövningsplatser": {},
        "Universitet & Högskolor": {},
        "Utbildning": {},
        "Vuxenutbildningar": {},
        "Yrkeshögskola": {},
        "Yrkesutbildningar": {}
    },
    "Kultur, Nöjen & Evenemang": {
        "Agenturer": {},
        "Artister & Artistförmedlingar": {},
        "Atg-ombud": {},
        "Av-produktion, -utrustningar": {},
        "Ballong-, Fallskärms- & Skärmflygning": {},
        "Barer & Pubar": {},
        "Barnaktiviteter": {},
        "Bibliotek": {},
        "Biljardhallar": {},
        "Biljardutrustning": {},
        "Biljettförsäljning": {},
        "Biljettombud": {},
        "Bingo": {},
        "Biografer": {},
        "Bokförlag": {},
        "Bokhandel": {},
        "Bowlinghallar": {},
        "Båtrundturer": {},
        "Casinon": {},
        "Catering": {},
        "Dans & Danslektioner": {},
        "Discjockey": {},
        "Diskoteksutrustning": {},
        "Djurparker & Botaniska trädgårdar": {},
        "Evenemang, eventbyråer": {},
        "Eventarrangörer": {},
        "Fest- & Samlingslokaler": {},
        "Festarrangörer": {},
        "Film- & Musikproduktion": {},
        "Fjällstationer": {},
        "Forsränning, flottfärder": {},
        "Friluftsaktiviteter & Äventyrssporter": {},
        "Författare": {},
        "Industridesigners, formgivare": {},
        "Kanoter": {},
        "Kanotuthyrning": {},
        "Klättercenter": {},
        "Konserthallar": {},
        "Konstgallerier": {},
        "Konstnärer & Illustratörer": {},
        "Konstnärlig, Litterär & Artistisk verksamhet": {},
        "Konstnärliga terapier": {},
        "Konstsmide": {},
        "Korsord": {},
        "Kultur- & Fritidsverksamhet": {},
        "Kulturhus": {},
        "Ljud- & Ljusanläggningar": {},
        "Ljudinspelning": {},
        "Ljusdesign, ljussättning": {},
        "Lotteriservice": {},
        "Läromedel": {},
        "Mediaproduktion": {},
        "Minigolfbanor": {},
        "Multimedia - produktioner": {},
        "Museer": {},
        "Musik - förmedling": {},
        "Musikförlag": {},
        "Nattklubbar & Diskotek": {},
        "Nöjesattraktioner": {},
        "Nöjesfält & Tivoli": {},
        "Paintball & Lasergame": {},
        "Radio - inspelning, produktion, reklam": {},
        "Radiobolag, -stationer": {},
        "Radioproduktion": {},
        "Scenografi, teaterdekor": {},
        "Skateparker": {},
        "Skivbolag": {},
        "Skjutbanor": {},
        "Spel & Lotterier": {},
        "Spelautomater, rouletter": {},
        "Spelhallar": {},
        "Spelombud, spelbolag": {},
        "Teaterförlag": {},
        "Teaterlektioner": {},
        "Teatrar": {},
        "Tidningar & Tidskrifter": {},
        "Tonsättare": {},
        "Travbanor & Galoppbanor": {},
        "Tryckeri-, bokbinderiutrustning": {},
        "Tryckerier & Bokbinderier": {},
        "TV-bolag": {},
        "Äventyr, naturupplevelser": {}
    },
    "Nödsituationer": {
        "Allergiläkare & Lungspecialister": {},
        "Allmänläkare": {},
        "Ambulans & Sjuktransport": {},
        "Barnavårdscentraler": {},
        "Barnläkare": {},
        "Bogsering, sjötransport": {},
        "Brand- & Räddningstjänst": {},
        "Brandredskap": {},
        "Brandskydd": {},
        "Brandstationer": {},
        "Bärgningar": {},
        "Datakommunikation": {},
        "Djurvård": {},
        "Fiberoptik": {},
        "Gynekologer & Förlossningsläkare": {},
        "Hudläkare & Könssjukdomar": {},
        "Hundvård": {},
        "Hörselhjälpmedel, hörapparater": {},
        "Inbrottsskydd": {},
        "Ip-telefoni": {},
        "Kardiologer & Hjärtspecialister": {},
        "Kassaskåp": {},
        "Kattvård": {},
        "Kirurger": {},
        "Kodlås, porttelefoner": {},
        "Krisjourer": {},
        "Larm & Bevakning": {},
        "Larmcentraler": {},
        "Laserbehandling, -kliniker": {},
        "Läkare": {},
        "Läkare - hälsokontroller, vaccinationer": {},
        "Läkare: spec. kompetens": {},
        "Läkare: spec. kompetens - anestesi, intensivvård": {},
        "Läkare: spec. kompetens - endokrinologi, hormonrubbningar": {},
        "Läkare: spec. kompetens - gastroenterologi, mag-, tarmsjukdomar": {},
        "Läkare: spec. kompetens - geriatrik, äldrevård": {},
        "Läkare: spec. kompetens - gynekologisk onkologi, tumörsjukdomar": {},
        "Läkare: spec. kompetens - hörselrubbningar": {},
        "Läkare: spec. kompetens - infektionssjukdomar": {},
        "Läkare: spec. kompetens - internmedicin": {},
        "Läkare: spec. kompetens - klinisk neurofysiologi": {},
        "Läkare: spec. kompetens - klinisk näringslära": {},
        "Läkare: spec. kompetens - neurologi": {},
        "Läkare: spec. kompetens - njursjukdomar": {},
        "Läkare: spec. kompetens - onkologi, tumörsjukdomar": {},
        "Läkare: spec. kompetens - ortopedi": {},
        "Läkare: spec. kompetens - radiologi, röntgendiagnostik": {},
        "Läkare: spec. kompetens - reumatologi": {},
        "Läkare: spec. kompetens - smärtlindring": {},
        "Läkare: spec. kompetens - ögonsjukdomar": {},
        "Läkare: spec. kompetens - öron-, näs-, halssjukdomar": {},
        "Lås- & Nyckelservice": {},
        "Märksystem - utrustningar": {},
        "Mödravård, barnmorskor, preventivmedelsrådgivning": {},
        "Mödravårdscentraler": {},
        "Neurologer": {},
        "Ordningsvakter": {},
        "Passersystem": {},
        "Plastikkirurger": {},
        "Polis": {},
        "Psykiatriker": {},
        "Sjukvårdsrådgivning": {},
        "Sjukvårdsupplysningar": {},
        "Skyddsrum, skyddsrumsmaterial": {},
        "Specialistläkare": {},
        "Specialisttandläkare": {},
        "Säkerhet - system, utrustning": {},
        "Tandhygienister": {},
        "Tandläkare": {},
        "Tele-, mobiloperatörer": {},
        "Telefon, fax, tillbehör": {},
        "Telekommunikation": {},
        "Urologer": {},
        "Utrymningssystem": {},
        "Veterinärer": {},
        "Värdetransporter": {},
        "Vårdcentraler": {},
        "Ögonläkare": {},
        "Öron- Näsa- & Halsläkare": {}
    },
    "Offentlig sektor & Samhälle": {
        "Allergiläkare & Lungspecialister": {},
        "Allmänläkare": {},
        "Alternativmedicin": {},
        "Ambulans & Sjuktransport": {},
        "Apotek": {},
        "Apoteksombud": {},
        "Arbetsgivarorganisationer": {},
        "Arbetslöshetskassor": {},
        "Barnavårdscentraler": {},
        "Barnläkare": {},
        "Begravningsbyråer": {},
        "Brand- & Räddningstjänst": {},
        "Brandredskap": {},
        "Brandskydd": {},
        "Brandstationer": {},
        "Bransch- & Yrkesorganisationer": {},
        "Budosporter": {},
        "Daghem, Förskolor & Fritidshem": {},
        "Datautbildning": {},
        "Dentalartiklar, -utrustning": {},
        "Dentallab": {},
        "Detektivbyråer": {},
        "Distriktssköterskor": {},
        "Djurskyddsföreningar": {},
        "Djurvård": {},
        "Domstolar": {},
        "Domstolsväsendet": {},
        "Fackliga organisationer": {},
        "Folkhögskolor": {},
        "Fotvård": {},
        "Frisk-, hälsovård": {},
        "Fritidsgård": {},
        "Fysioterapeut": {},
        "Församlingsexpeditioner": {},
        "Försvaret": {},
        "Försvarsindustri, -utrustning": {},
        "Försvarsmakten": {},
        "Försvarsorganisationer": {},
        "Försäkrings- & Arbetslöshetskassa": {},
        "Gaturenhållning, Avlopps- & Avfallshantering": {},
        "Gravstenar, gravvårdar": {},
        "Grundskolor": {},
        "Gymnasium": {},
        "Gynekologer & Förlossningsläkare": {},
        "Handelskammare": {},
        "Handikapporganisationer": {},
        "Healing": {},
        "Hemsjukvård": {},
        "Hemtjänst": {},
        "Hjälp-, Stöd- & Intresseorganisationer": {},
        "Hudläkare & Könssjukdomar": {},
        "Hundvård": {},
        "Husläkare": {},
        "Hypnos": {},
        "Högstadieskolor": {},
        "Hörselhjälpmedel, hörapparater": {},
        "Ideella föreningar, samhällstjänster": {},
        "Idrottsföreningar & Idrottsförbund": {},
        "Kardiologer & Hjärtspecialister": {},
        "Kattvård": {},
        "Kirurger": {},
        "Kommunal förvaltning": {},
        "Kommuner": {},
        "Komvux": {},
        "Konsumentvägledning": {},
        "Krematorium": {},
        "Krisjourer": {},
        "Kursverksamhet, studieförbund": {},
        "Landsting": {},
        "Laserbehandling, -kliniker": {},
        "Läkare": {},
        "Läkare - hälsokontroller, vaccinationer": {},
        "Läkare: spec. kompetens": {},
        "Läkare: spec. kompetens - allmänmedicin": {},
        "Läkare: spec. kompetens - anestesi, intensivvård": {},
        "Läkare: spec. kompetens - endokrinologi, hormonrubbningar": {},
        "Läkare: spec. kompetens - gastroenterologi, mag-, tarmsjukdomar": {},
        "Läkare: spec. kompetens - geriatrik, äldrevård": {},
        "Läkare: spec. kompetens - gynekologisk onkologi, tumörsjukdomar": {},
        "Läkare: spec. kompetens - hörselrubbningar": {},
        "Läkare: spec. kompetens - infektionssjukdomar": {},
        "Läkare: spec. kompetens - internmedicin": {},
        "Läkare: spec. kompetens - klinisk neurofysiologi": {},
        "Läkare: spec. kompetens - klinisk näringslära": {},
        "Läkare: spec. kompetens - neurologi": {},
        "Läkare: spec. kompetens - njursjukdomar": {},
        "Läkare: spec. kompetens - onkologi, tumörsjukdomar": {},
        "Läkare: spec. kompetens - ortopedi": {},
        "Läkare: spec. kompetens - radiologi, röntgendiagnostik": {},
        "Läkare: spec. kompetens - reumatologi": {},
        "Läkare: spec. kompetens - smärtlindring": {},
        "Läkare: spec. kompetens - ögonsjukdomar": {},
        "Läkare: spec. kompetens - öron-, näs-, halssjukdomar": {},
        "Läkemedelsinformation": {},
        "Länsmyndigheter": {},
        "Miljövård": {},
        "Missbruksrådgivning & Behandlingshem": {},
        "Motororganisationer": {},
        "Mödravård, barnmorskor, preventivmedelsrådgivning": {},
        "Mödravårdscentraler": {},
        "Neurologer": {},
        "Nykterhetsorganisationer": {},
        "Offentliga myndigheter": {},
        "Osteopater": {},
        "Pensionärsorganisationer": {},
        "Personliga assistenter": {},
        "Plastikkirurger": {},
        "Polis": {},
        "Politiska organisationer": {},
        "Psykiatriker": {},
        "Psykologer": {},
        "Psykoterapeuter": {},
        "Rehabilitering, habilitering": {},
        "Religiösa Samfund": {},
        "Renhållning, soputrustningar": {},
        "Samhälls- & Omsorgsverksamhet": {},
        "Samtalsterapeuter, samtalsbehandlare": {},
        "Seniorboende, äldreboende": {},
        "Sfi": {},
        "Sjukgymnaster": {},
        "Sjukhus & Lasarett": {},
        "Sjuksköterskor - legitimerade": {},
        "Sjukvård": {},
        "Sjukvårdsartiklar": {},
        "Skuldsanering": {},
        "Slamsugning": {},
        "Specialistläkare": {},
        "Specialisttandläkare": {},
        "Språkgranskning, -redigering": {},
        "Språkutbildning": {},
        "Studentföreningar": {},
        "Studentorganisationer": {},
        "Svenska kyrkan": {},
        "Särskola": {},
        "Tandhygienister": {},
        "Tandläkare": {},
        "Tandtekniska arbeten, laboratorier": {},
        "Tolkar - auktoriserade": {},
        "Tolkservice & Översättningar": {},
        "Trafiksäkerhet": {},
        "Ungdomsmottagning & Preventivmedelsrådgivning": {},
        "Universitet & Högskolor": {},
        "Urologer": {},
        "Utbildning": {},
        "Vattenverk": {},
        "Veterinärer": {},
        "Vuxenutbildningar": {},
        "Vårdcentraler": {},
        "Äldreomsorg": {},
        "Ögonläkare": {},
        "Öppen Hälso- & Sjukvård": {},
        "Öron- Näsa- & Halsläkare": {}
    },
    "Resor & Hotell": {
        "Ambassader": {},
        "Amerikansk restaurang": {},
        "Asiatiska restauranger": {},
        "Bed & breakfast": {},
        "Biluthyrning": {},
        "Bussar - Linjetrafik & Expressbussar": {},
        "Bussbolag": {},
        "Bussresearrangörer & Bussuthyrning": {},
        "Bärhandel, odlare": {},
        "Båtlinjer, färjelinjer": {},
        "Båttaxi": {},
        "Båtuthyrning": {},
        "Campingplatser": {},
        "Charkuterivaror": {},
        "Charter- & Taxiflyg": {},
        "Choklad": {},
        "Crossover restaurang": {},
        "Delikatesser": {},
        "Diskoteksutrustning": {},
        "Ekologiska livsmedel": {},
        "Fisk, skaldjur": {},
        "Fisk, skaldjur - grossister": {},
        "Fjäderfä - kläckerier, uppfödning": {},
        "Flyg": {},
        "Flygbolag": {},
        "Flygplan, utrustningar": {},
        "Flygplatser": {},
        "Flygskolor, flygklubbar": {},
        "Flygtransporter": {},
        "Foodtruck": {},
        "Fordonsuthyrning": {},
        "Fruktleverantörer": {},
        "Färdiglagad mat": {},
        "Färjetrafik & Rederier": {},
        "Glass": {},
        "Glassbarer, -serveringar": {},
        "Guider": {},
        "Handikapptransporter": {},
        "Hotell & Pensionat": {},
        "Husbils-, Släpvagns- & Husvagnsuthyrning": {},
        "Husmanskost": {},
        "Hygienartiklar": {},
        "Internationell restaurang": {},
        "Internetcaféer, hotspots": {},
        "Japansk restaurang": {},
        "Juicebarer": {},
        "Järnväg, spårväg - arbete, material": {},
        "Järnvägsstationer": {},
        "Kaffeautomater": {},
        "Kafferosterier": {},
        "Kebab": {},
        "Kiosker": {},
        "Konditorier": {},
        "Konferens- & Mässarrangörer": {},
        "Konferensanläggningar & Kursgårdar": {},
        "Konferenser & Mässor": {},
        "Konferenslokaler": {},
        "Konferensutrustning": {},
        "Kongressarrangörer": {},
        "Korvkiosk": {},
        "Kosttillskott - tillverkare, grossister": {},
        "Kryddor": {},
        "Kursgårdar": {},
        "Kött-, slakteriprodukter": {},
        "Lantbruksförnödenheter": {},
        "Libanesiska restauranger": {},
        "Limousineservice": {},
        "Livsmedelsindustrimaskiner": {},
        "Lunchrestaurang": {},
        "Matbutiker": {},
        "Matkassar": {},
        "Musterier": {},
        "Mäss-, utställningsproduktion": {},
        "Nudelrestaurang": {},
        "Organiska livsmedel": {},
        "Pensionat": {},
        "Personalmatsalar": {},
        "Rawfood": {},
        "Resebyråer & Charterresor": {},
        "Rökerier": {},
        "Salladsbar": {},
        "Skidanläggningar": {},
        "Smörgåsaffärer": {},
        "Smörgåsbar": {},
        "Sockerbruk": {},
        "SPA-anläggningar": {},
        "Spannmål, spannmålsprodukter": {},
        "Steakhouse": {},
        "Storhushållsvaror": {},
        "Stugor & Stugbyar": {},
        "Stuverier": {},
        "Taxi": {},
        "Turistarrangemang": {},
        "Turistattraktioner, utflyktsmål": {},
        "Turistbyråer": {},
        "Tåg- & Spårtrafik": {},
        "Tågresor - tågtransporter": {},
        "Vandrarhem": {},
        "Veganska restauranger": {},
        "Vegetariska restauranger": {},
        "Vietnamesiska restauranger": {},
        "Växlingskontor": {},
        "Äggproduktion": {},
        "Ölimportörer, -grossister": {}
    },
    "Restaurang, Mat & Dryck": {
        "Bagerier": {},
        "Barer & Pubar": {},
        "Bryggerier, Vin- & Spritproducenter": {},
        "Caféer": {},
        "Catering": {},
        "Dryckesvaruindustrier": {},
        "Food court": {},
        "Franska restauranger": {},
        "Frukt-, Bär- & Grönsaksodlingar": {},
        "Grekiska restauranger": {},
        "Hamburgerrestauranger & Gatukök": {},
        "Hälsokost": {},
        "Indiska restauranger": {},
        "Italienska restauranger": {},
        "Jour- & Servicebutiker": {},
        "Juice- & Saftindustrier": {},
        "Kaffe- & Teindustrier": {},
        "Kinesiska restauranger": {},
        "Konfektyr & Godisaffärer": {},
        "Kontinentala restauranger": {},
        "Lant- & Jordbruk": {},
        "Livsmedelsbutiker": {},
        "Livsmedelsindustrier": {},
        "Mat- & Dryckesautomater": {},
        "Mejerier": {},
        "Mineralvatten- & Läskedryckesindustrier": {},
        "Nattklubbar & Diskotek": {},
        "Pizzerior": {},
        "Restauranger & Serveringar": {},
        "Saluhallar": {},
        "Slakterier": {},
        "Sushirestauranger": {},
        "Svenska restauranger": {},
        "Systembolag & Ombud": {},
        "Thairestauranger": {}
    },
    "Sport & Hobby": {
        "Akvarium, akvarieuthyrning": {},
        "Arkiv-, släktforskning": {},
        "Atg-ombud": {},
        "Badmintonhallar": {},
        "Badplats": {},
        "Ballong-, Fallskärms- & Skärmflygning": {},
        "Barnaktiviteter": {},
        "Biljardhallar": {},
        "Biljardutrustning": {},
        "Bingo": {},
        "Bowlinghallar": {},
        "Budosporter": {},
        "Båtklubbar": {},
        "Båtrundturer": {},
        "Casinon": {},
        "Curling - hallar, banor": {},
        "Cykelförsäljning & Cykelverkstäder": {},
        "Cykeluthyrning": {},
        "Cyklar": {},
        "Cyklar - reparationer": {},
        "Cyklar - uthyrning": {},
        "Dans & Danslektioner": {},
        "Djuraffärer": {},
        "Djurfoder, artiklar": {},
        "Djurparker & Botaniska trädgårdar": {},
        "Djurpensionat": {},
        "Djuruppfödning": {},
        "Dykeriarbeten": {},
        "Dykerier": {},
        "Dykning, dykutbildning": {},
        "Dykutrustning": {},
        "Filmlaboratorier": {},
        "Fisketurer": {},
        "Fjällstationer": {},
        "Forsränning, flottfärder": {},
        "Fotbollsplaner": {},
        "Foto": {},
        "Fotoaffärer": {},
        "Fotografer": {},
        "Friluftsaktiviteter & Äventyrssporter": {},
        "Garner, Tyger & Sybehör": {},
        "Go Kart": {},
        "Golf": {},
        "Golf - bangolf, minigolf": {},
        "Golfbanor & Golfklubbar": {},
        "Golfbutiker": {},
        "Gym & Motion": {},
        "Handarbeten": {},
        "Hobbyartiklar": {},
        "Hovslagare": {},
        "Hunddagis": {},
        "Hundpensionat": {},
        "Husdjursskötsel": {},
        "Hästsportbutiker": {},
        "Hästuppfödningar & Stuterier": {},
        "Ideella föreningar, samhällstjänster": {},
        "Idrottsföreningar & Idrottsförbund": {},
        "Instrument": {},
        "Ishallar": {},
        "Jakt, jaktredskap": {},
        "Jakt- & Fiskeutrustning": {},
        "Kanoter": {},
        "Kanotuthyrning": {},
        "Kattpensionat": {},
        "Kattuppfödning": {},
        "Kennlar & Kennelklubbar": {},
        "Klättercenter": {},
        "Konstgallerier": {},
        "Leksaker": {},
        "Leksaks-, Spel- & Hobbybutiker": {},
        "Lotteriservice": {},
        "Minigolfbanor": {},
        "Mopedförsäljning & Mopedverkstäder": {},
        "Motionsanläggningar, friluftsgårdar": {},
        "Motorsportbanor": {},
        "Museer": {},
        "Musik - distribution": {},
        "Musik - förmedling": {},
        "Musik - skivbutiker": {},
        "Musikaffärer": {},
        "Musikförlag": {},
        "Musikinstrument, -tillbehör": {},
        "Musikinstrument, -tillbehör - reparationer": {},
        "Paintball & Lasergame": {},
        "Pianon, orglar": {},
        "Pianostämmare": {},
        "Pyroteknik & Fyrverkerier": {},
        "Rackethallar": {},
        "Ridklubbar & Ridskolor": {},
        "Sadelmakare": {},
        "Scoutkårer": {},
        "Segelmakeri": {},
        "Simhallar & Utomhusbad": {},
        "Simskolor": {},
        "Skateparker": {},
        "Skidanläggningar": {},
        "Skidor, snowboard": {},
        "Skivbolag": {},
        "Skjutbanor": {},
        "Släktforskning": {},
        "Spel & Lotterier": {},
        "Spelautomater, rouletter": {},
        "Spelcenter, laserspel": {},
        "Spelhallar": {},
        "Spelombud, spelbolag": {},
        "Sport- & Idrottsanläggningar": {},
        "Sport- & Idrottshallar": {},
        "Sportaffärer & Friluftsutrustning": {},
        "Sportfiske": {},
        "Squashhallar": {},
        "Symaskiner": {},
        "Tai chi": {},
        "Tavlor & Ramar": {},
        "Tennisklubbar & Tennisbanor": {},
        "Travbanor & Galoppbanor": {},
        "TV- & Dataspel": {},
        "Tält": {},
        "Vapen, ammunition - utrustningar": {},
        "Vilt, fågel": {},
        "Viltvård & Fiskevatten": {},
        "Yoga & Meditation": {},
        "Zooaffärer": {},
        "Zoologiska artiklar - tillverkare, grossister": {},
        "Äventyr, naturupplevelser": {}
    }
}
